auth-server: http://localhost:8089/uaa # sso-server地址
spring:
  application:
    name: client
security:
  oauth2:
    client:
      client-id: merryyou
      client-secret: merryyou
      user-authorization-uri: ${auth-server}/oauth/authorize #请求认证的地址
      access-token-uri: ${auth-server}/oauth/token #请求令牌的地址
      registered-redirect-uri: http://localhost:8088
    resource:
#      token-info-uri:  ${auth-server}/oauth/check_token
      jwt:
        key-uri:  ${auth-server}/oauth/token_key
      filter-order: 3
      user-info-uri: http://localhost:8080/uaa/user
logging:
  level:
    org.springframework: debug
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
server:
  port: 8088
